/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizsystem.ui.gfx;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import model.Chart;
import model.ModelHelper;
import model.Question;
import model.QuestionResourse;
import model.Resourse;

/**
 *
 * @author Mithila
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        control_area = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        view = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sign_out = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        action_area = new javax.swing.JPanel();
        Add_Ques = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addQues_question = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        add_ans1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        add_ans2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        add_ans3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        add_cur_ans = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        addQues = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        enable_server = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        start_server = new javax.swing.JButton();
        View_Ques = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Delete_Ques = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        delete_ques_no = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        deleteQues_question = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        delete_ans = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        delete_ans2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        delete_ans3 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        delete_cur_ans = new javax.swing.JTextField();
        deleteQues = new javax.swing.JButton();
        Clear3 = new javax.swing.JButton();
        Edit_Ques = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ques_no = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        editQues_question = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        edit_ans = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        edit_ans2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        edit_ans3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        edit_cur_ans = new javax.swing.JTextField();
        updateQues = new javax.swing.JButton();
        Clear2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base.setBackground(new java.awt.Color(255, 255, 255));

        control_area.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QuizSystem");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/admin.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin Penel");

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Add Questionar");

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Edit Questionar");

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Delete Questionar");

        javax.swing.GroupLayout deleteLayout = new javax.swing.GroupLayout(delete);
        delete.setLayout(deleteLayout);
        deleteLayout.setHorizontalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        deleteLayout.setVerticalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("View Results");

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Enable Server");

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sign_out.setBackground(new java.awt.Color(255, 255, 255));
        sign_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_outMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("SignOut");

        javax.swing.GroupLayout sign_outLayout = new javax.swing.GroupLayout(sign_out);
        sign_out.setLayout(sign_outLayout);
        sign_outLayout.setHorizontalGroup(
            sign_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sign_outLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sign_outLayout.setVerticalGroup(
            sign_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sign_outLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout control_areaLayout = new javax.swing.GroupLayout(control_area);
        control_area.setLayout(control_areaLayout);
        control_areaLayout.setHorizontalGroup(
            control_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_areaLayout.createSequentialGroup()
                .addGroup(control_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(control_areaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(control_areaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(control_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sign_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        control_areaLayout.setVerticalGroup(
            control_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_areaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(control_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(control_areaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(control_areaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGap(37, 37, 37)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sign_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        action_area.setLayout(new java.awt.CardLayout());

        Add_Ques.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel10.setText("Add Questionar");

        addQues_question.setColumns(20);
        addQues_question.setRows(5);
        jScrollPane1.setViewportView(addQues_question);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Type your question");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Type answers for your question");

        add_ans1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel17.setText("Answer 1: ");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setText("Answer 2: ");

        add_ans2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setText("Answer 3: ");

        add_ans3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel20.setText("Answer : ");

        add_cur_ans.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setText("Type currect answer for your question");

        addQues.setBackground(new java.awt.Color(0, 102, 204));
        addQues.setForeground(new java.awt.Color(255, 255, 255));
        addQues.setText("Add");
        addQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuesActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(0, 102, 204));
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Add_QuesLayout = new javax.swing.GroupLayout(Add_Ques);
        Add_Ques.setLayout(Add_QuesLayout);
        Add_QuesLayout.setHorizontalGroup(
            Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_QuesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(Add_QuesLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(add_ans2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Add_QuesLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(add_ans1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Add_QuesLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(add_ans3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Add_QuesLayout.createSequentialGroup()
                                .addComponent(addQues)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Clear))
                            .addGroup(Add_QuesLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(add_cur_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Add_QuesLayout.setVerticalGroup(
            Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_QuesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addGap(19, 19, 19)
                .addGroup(Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(add_ans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(add_ans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(add_ans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(add_cur_ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(Add_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addQues)
                    .addComponent(Clear))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        action_area.add(Add_Ques, "card2");

        enable_server.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setText("Enable Server");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Click the bellow button to start server");

        start_server.setBackground(new java.awt.Color(0, 102, 204));
        start_server.setForeground(new java.awt.Color(255, 255, 255));
        start_server.setText("Start");
        start_server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_serverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enable_serverLayout = new javax.swing.GroupLayout(enable_server);
        enable_server.setLayout(enable_serverLayout);
        enable_serverLayout.setHorizontalGroup(
            enable_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enable_serverLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(205, 205, 205))
            .addGroup(enable_serverLayout.createSequentialGroup()
                .addGroup(enable_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enable_serverLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14))
                    .addGroup(enable_serverLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(start_server)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        enable_serverLayout.setVerticalGroup(
            enable_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enable_serverLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(203, 203, 203)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(start_server)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        action_area.add(enable_server, "card6");

        View_Ques.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setText("View Results");

        javax.swing.GroupLayout View_QuesLayout = new javax.swing.GroupLayout(View_Ques);
        View_Ques.setLayout(View_QuesLayout);
        View_QuesLayout.setHorizontalGroup(
            View_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_QuesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addContainerGap(500, Short.MAX_VALUE))
        );
        View_QuesLayout.setVerticalGroup(
            View_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_QuesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel13)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        action_area.add(View_Ques, "card5");

        Delete_Ques.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel12.setText("Delete Questionar");

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel38.setText("Select question no");

        delete_ques_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ques_noActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel39.setText("Type your question");

        deleteQues_question.setColumns(20);
        deleteQues_question.setRows(5);
        jScrollPane4.setViewportView(deleteQues_question);

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel40.setText("Type answers for your question");

        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel41.setText("Answer 1: ");

        delete_ans.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel42.setText("Answer 2: ");

        delete_ans2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel43.setText("Answer 3: ");

        delete_ans3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel44.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel44.setText("Type currect answer for your question");

        jLabel45.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel45.setText("Answer : ");

        delete_cur_ans.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        deleteQues.setBackground(new java.awt.Color(0, 102, 204));
        deleteQues.setForeground(new java.awt.Color(255, 255, 255));
        deleteQues.setText("Delete");
        deleteQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteQuesActionPerformed(evt);
            }
        });

        Clear3.setBackground(new java.awt.Color(0, 102, 204));
        Clear3.setForeground(new java.awt.Color(255, 255, 255));
        Clear3.setText("Clear");
        Clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Delete_QuesLayout = new javax.swing.GroupLayout(Delete_Ques);
        Delete_Ques.setLayout(Delete_QuesLayout);
        Delete_QuesLayout.setHorizontalGroup(
            Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_QuesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addContainerGap(429, Short.MAX_VALUE))
            .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Delete_QuesLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Delete_QuesLayout.createSequentialGroup()
                            .addComponent(deleteQues)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Clear3))
                        .addComponent(jLabel44)
                        .addGroup(Delete_QuesLayout.createSequentialGroup()
                            .addComponent(jLabel42)
                            .addGap(18, 18, 18)
                            .addComponent(delete_ans2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel40)
                        .addComponent(jLabel39)
                        .addGroup(Delete_QuesLayout.createSequentialGroup()
                            .addComponent(jLabel41)
                            .addGap(18, 18, 18)
                            .addComponent(delete_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Delete_QuesLayout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addGap(18, 18, 18)
                                .addComponent(delete_ans3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Delete_QuesLayout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(18, 18, 18)
                                .addComponent(delete_cur_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Delete_QuesLayout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delete_ques_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        Delete_QuesLayout.setVerticalGroup(
            Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_QuesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addContainerGap(561, Short.MAX_VALUE))
            .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Delete_QuesLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(delete_ques_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38))
                    .addGap(45, 45, 45)
                    .addComponent(jLabel39)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(jLabel40)
                    .addGap(19, 19, 19)
                    .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(delete_ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42)
                        .addComponent(delete_ans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel43)
                        .addComponent(delete_ans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37)
                    .addComponent(jLabel44)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(delete_cur_ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(Delete_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteQues)
                        .addComponent(Clear3))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        action_area.add(Delete_Ques, "card4");

        Edit_Ques.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setText("Edit Questionar");

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setText("Select question no");

        ques_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_noActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel31.setText("Type your question");

        editQues_question.setColumns(20);
        editQues_question.setRows(5);
        jScrollPane3.setViewportView(editQues_question);

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel32.setText("Type answers for your question");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel33.setText("Answer 1: ");

        edit_ans.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel34.setText("Answer 2: ");

        edit_ans2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel35.setText("Answer 3: ");

        edit_ans3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setText("Type currect answer for your question");

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel37.setText("Answer : ");

        edit_cur_ans.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        updateQues.setBackground(new java.awt.Color(0, 102, 204));
        updateQues.setForeground(new java.awt.Color(255, 255, 255));
        updateQues.setText("Update");
        updateQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateQuesActionPerformed(evt);
            }
        });

        Clear2.setBackground(new java.awt.Color(0, 102, 204));
        Clear2.setForeground(new java.awt.Color(255, 255, 255));
        Clear2.setText("Clear");
        Clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Edit_QuesLayout = new javax.swing.GroupLayout(Edit_Ques);
        Edit_Ques.setLayout(Edit_QuesLayout);
        Edit_QuesLayout.setHorizontalGroup(
            Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Edit_QuesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addContainerGap(466, Short.MAX_VALUE))
            .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Edit_QuesLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Edit_QuesLayout.createSequentialGroup()
                            .addComponent(updateQues)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Clear2))
                        .addComponent(jLabel36)
                        .addGroup(Edit_QuesLayout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addGap(18, 18, 18)
                            .addComponent(edit_ans2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel32)
                        .addComponent(jLabel31)
                        .addGroup(Edit_QuesLayout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addGap(18, 18, 18)
                            .addComponent(edit_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Edit_QuesLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(edit_ans3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Edit_QuesLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(18, 18, 18)
                                .addComponent(edit_cur_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Edit_QuesLayout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ques_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        Edit_QuesLayout.setVerticalGroup(
            Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Edit_QuesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addContainerGap(561, Short.MAX_VALUE))
            .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Edit_QuesLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ques_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30))
                    .addGap(45, 45, 45)
                    .addComponent(jLabel31)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(jLabel32)
                    .addGap(19, 19, 19)
                    .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(edit_ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(edit_ans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(edit_ans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37)
                    .addComponent(jLabel36)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(edit_cur_ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(Edit_QuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateQues)
                        .addComponent(Clear2))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        action_area.add(Edit_Ques, "card3");

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(control_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(action_area, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(action_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(control_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        Add_Ques.setVisible(true);
        Edit_Ques.setVisible(false);
        Delete_Ques.setVisible(false);
        View_Ques.setVisible(false);
        enable_server.setVisible(false);
    }//GEN-LAST:event_addMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        Edit_Ques.setVisible(true);
        Delete_Ques.setVisible(false);
        View_Ques.setVisible(false);
        enable_server.setVisible(false);
        Add_Ques.setVisible(false);
        fillComba();
    }//GEN-LAST:event_editMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        Delete_Ques.setVisible(true);
        Edit_Ques.setVisible(false);
        View_Ques.setVisible(false);
        enable_server.setVisible(false);
        Add_Ques.setVisible(false);
        fillComba2();
    }//GEN-LAST:event_deleteMouseClicked

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
       
            //         Delete_Ques.setVisible(false);
//         Edit_Ques.setVisible(false);
//         View_Ques.setVisible(true);
//         enable_server.setVisible(false);
//         Add_Ques.setVisible(false);
            Chart ch = new Chart("Result Statistic");
            ch.setSize(800, 400);
            ch.setLocationRelativeTo(null);
            ch.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            ch.setVisible(true);
      
           
    }//GEN-LAST:event_viewMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        Delete_Ques.setVisible(false);
        Edit_Ques.setVisible(false);
        View_Ques.setVisible(false);
        enable_server.setVisible(true);
        Add_Ques.setVisible(false);
    }//GEN-LAST:event_profileMouseClicked

    private void sign_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_outMouseClicked
        SignIn si = new SignIn();
        si.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sign_outMouseClicked

    private void addQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuesActionPerformed
        String question, ans1, ans2, ans3, cur_ans;
        question = addQues_question.getText();
        ans1 = add_ans1.getText();
        ans2 = add_ans2.getText();
        ans3 = add_ans3.getText();
        cur_ans = add_cur_ans.getText();

        if (question.equalsIgnoreCase("") || ans1.equalsIgnoreCase("") || ans2.equalsIgnoreCase("") || ans3.equalsIgnoreCase("") || cur_ans.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "You have to fill each fields!");
        } else {
            ModelHelper modelHelper = new ModelHelper();
            modelHelper.addQuiz(question, ans1, ans2, ans3, cur_ans);
        }
    }//GEN-LAST:event_addQuesActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        addQues_question.setText(null);
        add_ans1.setText(null);
        add_ans2.setText(null);
        add_ans3.setText(null);
        add_cur_ans.setText(null);
    }//GEN-LAST:event_ClearActionPerformed

    private void start_serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_serverActionPerformed
        try {
            Resourse questionResourse = new QuestionResourse();
            Registry reg = LocateRegistry.createRegistry(9000);
            reg.rebind("MyQuestionServer", questionResourse);
            System.out.println("Server is running....");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_start_serverActionPerformed

    private void updateQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateQuesActionPerformed
        String question, ans1, ans2, ans3, cur_ans, id;
        question = editQues_question.getText();
        ans1 = edit_ans.getText();
        ans2 = edit_ans2.getText();
        ans3 = edit_ans3.getText();
        cur_ans = edit_cur_ans.getText();
        id = ques_no.getSelectedItem().toString();

        if (question.equalsIgnoreCase("") || ans1.equalsIgnoreCase("") || ans2.equalsIgnoreCase("") || ans3.equalsIgnoreCase("") || cur_ans.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "You have to fill each fields!");
        } else {
            ModelHelper modelHelper = new ModelHelper();
            modelHelper.updateQuiz(question, ans1, ans2, ans3, cur_ans, id);
        }
    }//GEN-LAST:event_updateQuesActionPerformed

    private void Clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear2ActionPerformed
        addQues_question.setText(null);
        add_ans1.setText(null);
        add_ans2.setText(null);
        add_ans3.setText(null);
        add_cur_ans.setText(null);
    }//GEN-LAST:event_Clear2ActionPerformed

    private void ques_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_noActionPerformed
        ModelHelper modelHelper = new ModelHelper();
        int id = Integer.parseInt(ques_no.getSelectedItem().toString());
        Question question = modelHelper.getQuestion(id);
        editQues_question.setText(question.getQuestion());
        edit_ans.setText(question.getAns1());
        edit_ans2.setText(question.getAns2());
        edit_ans3.setText(question.getAns3());
        edit_cur_ans.setText(question.getCurrect_ans1());
    }//GEN-LAST:event_ques_noActionPerformed

    private void delete_ques_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ques_noActionPerformed
        ModelHelper modelHelper = new ModelHelper();
        int id = Integer.parseInt(delete_ques_no.getSelectedItem().toString());
        Question question = modelHelper.getQuestion(id);
        deleteQues_question.setText(question.getQuestion());
        delete_ans.setText(question.getAns1());
        delete_ans2.setText(question.getAns2());
        delete_ans3.setText(question.getAns3());
        delete_cur_ans.setText(question.getCurrect_ans1());
    }//GEN-LAST:event_delete_ques_noActionPerformed

    private void deleteQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteQuesActionPerformed
        String question, ans1, ans2, ans3, cur_ans, id;
        question = deleteQues_question.getText();
        ans1 = delete_ans.getText();
        ans2 = delete_ans2.getText();
        ans3 = delete_ans3.getText();
        cur_ans = delete_cur_ans.getText();
        id = delete_ques_no.getSelectedItem().toString();

        if (question.equalsIgnoreCase("") || ans1.equalsIgnoreCase("") || ans2.equalsIgnoreCase("") || ans3.equalsIgnoreCase("") || cur_ans.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "You have to fill each fields!");
        } else {
            ModelHelper modelHelper = new ModelHelper();
            modelHelper.deleteQuiz(id);
        }
    }//GEN-LAST:event_deleteQuesActionPerformed

    private void Clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear3ActionPerformed
        deleteQues_question.setText(null);
        delete_ans.setText(null);
        delete_ans2.setText(null);
        delete_ans3.setText(null);
        delete_cur_ans.setText(null);
    }//GEN-LAST:event_Clear3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    public void fillComba() {
        ModelHelper modelHelper = new ModelHelper();
        ArrayList<String> lists = modelHelper.getQuestionNumbers();

        for (String item : lists) {
            ques_no.addItem(item);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_Ques;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Clear2;
    private javax.swing.JButton Clear3;
    private javax.swing.JPanel Delete_Ques;
    private javax.swing.JPanel Edit_Ques;
    private javax.swing.JPanel View_Ques;
    private javax.swing.JPanel action_area;
    private javax.swing.JPanel add;
    private javax.swing.JButton addQues;
    private javax.swing.JTextArea addQues_question;
    private javax.swing.JTextField add_ans1;
    private javax.swing.JTextField add_ans2;
    private javax.swing.JTextField add_ans3;
    private javax.swing.JTextField add_cur_ans;
    private javax.swing.JPanel base;
    private javax.swing.JPanel control_area;
    private javax.swing.JPanel delete;
    private javax.swing.JButton deleteQues;
    private javax.swing.JTextArea deleteQues_question;
    private javax.swing.JTextField delete_ans;
    private javax.swing.JTextField delete_ans2;
    private javax.swing.JTextField delete_ans3;
    private javax.swing.JTextField delete_cur_ans;
    private javax.swing.JComboBox<String> delete_ques_no;
    private javax.swing.JPanel edit;
    private javax.swing.JTextArea editQues_question;
    private javax.swing.JTextField edit_ans;
    private javax.swing.JTextField edit_ans2;
    private javax.swing.JTextField edit_ans3;
    private javax.swing.JTextField edit_cur_ans;
    private javax.swing.JPanel enable_server;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel profile;
    private javax.swing.JComboBox<String> ques_no;
    private javax.swing.JPanel sign_out;
    private javax.swing.JButton start_server;
    private javax.swing.JButton updateQues;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables

    private void fillComba2() {
        ModelHelper modelHelper = new ModelHelper();
        ArrayList<String> lists = modelHelper.getQuestionNumbers();

        for (String item : lists) {
            delete_ques_no.addItem(item);
        }
    }
}
